name: Deploy Docker Image to GCP VM

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS}}

      # Step 3: Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      # Step 4: Update VM with Docker Image and Deploy Container
      - name: Deploy Docker Image to VM
        run: |
          gcloud compute instances update-container docker-vm \
            --zone=${{ secrets.GCP_ZONE }} \
            --container-image=${{ secrets.DOCKER_IMAGE }}

      # Step 5: Restart VM to Apply Container Update (optional)
      - name: Restart VM to Apply Container Update
        run: |
          gcloud compute instances reset docker-vm \
            --zone=${{ secrets.GCP_ZONE }}
