name: Deploy Docker Image to GCP VM

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS}}

      # Step 3: Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

 # Step 4: Create VM with Docker Container
      - name: Create VM and Deploy Docker Container
        run: |
          gcloud compute instances create-with-container docker-vm1 \
            --zone=${{ secrets.GCP_ZONE }} \
            --container-image=${{ secrets.DOCKER_IMAGE }} 
   


      - name: Run Smoke Tests (Check if app is up)
        run: |
          IP_ADDRESS=$(gcloud compute instances describe docker-vm1 --zone=${{ secrets.GCP_ZONE }} --format="get(networkInterfaces[0].accessConfigs[0].natIP)")
          echo "Checking if app is running at http://$IP_ADDRESS"
          curl --silent --fail http://$IP_ADDRESS || exit 1  # Fail if unable to access the app

       
